### PR TITLE
Cydia.yml

### PR DESCRIPTION
**Pull request by 8ss**
"/Applications/Cydia.app"
   "/Applications/blackra1n.app"
   "/Applications/FakeCarrier.app"
   "/Applications/Icy.app"
   "/Applications/IntelliScreen.app"
   "/Applications/MxTube.app"
   "/Applications/RockApp.app"
   "/Applications/SBSetttings.app"
   "/Applications/WinterBoard.app"
   "/private/var/lib/apt/"
   "/private/var/lib/cydia/"
   "/private/var/mobileLibrary/SBSettingsThemes/"
   "/private/var/tmp/cydia.log"
   "/private/var/stash/"
   "/usr/libexec/cydia/"
   "/usr/bin/sshd"
   "/usr/sbin/sshd"
   "/usr/libexec/cydia/"
   "/usr/libexec/sftp-server"
   "/Systetem/Library/LaunchDaemons/com.ikey.bbot.plist"
   "/System/Library/LaunchDaemons/com.saurik.Cydia.Startup.plist"
   "/Library/MobileSubstrate/MobileSubstrate.dylib"
   "/var/cache/apt/"
   "/var/lib/apt/"
   "/var/lib/cydia/"
   "/var/log/syslog"
   "/private/var/cache/apt/"
   "/private/var/lib/apt/"
   "/private/var/lib/cydia/"
   "/private/var/log/syslog"
   "/bin/bash"
   "/bin/sh"
   "/private/etc/apt/"
   "/etc/apt/"
   "/private/etc/ssh/sshd_config"
   "/etc/ssh/sshd_config"
   "/usr/libexec/ssh-keysign"
   "/Applications/Snoop-itConfig.app"
   "/Library/MobileSubstrate/DynamicLibraries/xCon.dylib"
   "/private/etc/dpkg/origins/debian"
   "/etc/apt"
   "/usr/bin/ssh"
   "/var/cache/apt"
   "/var/lib/apt"
   "/var/lib/cydia"
   "/var/tmp/cydia.log"

### CODE REVIEW

**Comment by zumplxs** [comment]
[https://github.com/lapsap/ios_security_detection/pull/1#issue-399593220](url)

**Comment by mehmeteren0709** [comment]
Mehmeterengumus2007@gmail.com

**Review by mehmeteren0709 — COMMENTED** [review]
Mehmeterengumus2007@gmail.com

**Review by mehmeteren0709 — APPROVED** [review]
Mehmeterengumus2007@gmail.com

**Review by Chantha2323 — APPROVED** [review]

**Pull request merged**
